# Base image: Use the built "kairin/001:15-flash-attention" image
FROM kairin/001:15-flash-attention

# Copy the list_installed_apps.sh script into the container
COPY list_installed_apps.sh /usr/local/bin/list_installed_apps.sh

# Make the script executable
RUN chmod +x /usr/local/bin/list_installed_apps.sh

# Set the script to run when the container starts
CMD ["/usr/local/bin/list_installed_apps.sh"]
